'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Birometric_Entrance_Record_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _103775_edit_user_half_icon__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("103775_edit_user_half_icon (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _103780_profile_user_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("103780_profile_user_icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _103780_profile_user_icon__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("103780_profile_user_icon (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _103780_profile_user_icon__1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("103780_profile_user_icon (1)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _103780_profile_user_icon__1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("103780_profile_user_icon (1)3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _186390_refresh_sync_icon__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("186390_refresh_sync_icon (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _186390_refresh_sync_icon__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("186390_refresh_sync_icon (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1904654_cancel_close_cross_delete_reject_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1904654_cancel_close_cross_delete_reject_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1904654_cancel_close_cross_delete_reject_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1904654_cancel_close_cross_delete_reject_icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1904654_cancel_close_cross_delete_reject_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1904654_cancel_close_cross_delete_reject_icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1904665_bar_lines_list_menu_nav_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1904665_bar_lines_list_menu_nav_icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1904666_calculate_close_delete_hide_minimize_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1904666_calculate_close_delete_hide_minimize_icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2024657_cable_usb_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2024657_cable_usb_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2124274_process_document_app_essential_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2124274_process_document_app_essential_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _216468_close_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("216468_close_icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _216468_close_icon__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("216468_close_icon (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2202256_bin_cancel_delete_garbage_recycle_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2202256_bin_cancel_delete_garbage_recycle_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2742911__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2742911 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2742911__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2742911 (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _326558_blank_check_box_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("326558_blank_check_box_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _326691_all_select_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("326691_all_select_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4064143_usb_connection_port_hardware_icon__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4064143_usb_connection_port_hardware_icon (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4064143_usb_connection_port_hardware_icon__2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4064143_usb_connection_port_hardware_icon (2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4417105_cdn_connected_globe_dots_earth_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4417105_cdn_connected_globe_dots_earth_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5027835_analytics_chart_graph_statistics_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5027835_analytics_chart_graph_statistics_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5027835_analytics_chart_graph_statistics_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5027835_analytics_chart_graph_statistics_icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5027835_analytics_chart_graph_statistics_icon__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5027835_analytics_chart_graph_statistics_icon (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6oa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6oa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9024006_user_circle_fill_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9024006_user_circle_fill_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9024009_user_circle_plus_fill_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9024009_user_circle_plus_fill_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9044938_operations_record_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9044938_operations_record_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9104261_offline_server_cloud_database_disconnect_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9104261_offline_server_cloud_database_disconnect_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9104261_offline_server_cloud_database_disconnect_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9104261_offline_server_cloud_database_disconnect_icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about_us_icon_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about-us-icon-15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about_us_icon_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about-us-icon-9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about_us_icon_91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about-us-icon-91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Disconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disconnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DzUd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DzUd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FB_IMG_1687753628437_removebg_preview__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FB_IMG_1687753628437-removebg-preview (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property slide1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slide1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VZvw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VZvw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property XOsX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XOsX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
